### ISSUE TITLE
TypeError: Cannot read property 'corked' of undefined

### ISSUE THREAD

**Issue by malandrew** [mafintosh/tar-stream#32]
when trying to do the following:

```
            var readStream = fs.createReadStream(tarballPath);
            var extractStream = tar.extract(nodeModulesPath);

            readStream
                .pipe(zlib.createGunzip())
                .pipe(extractStream);

            readStream.on('error', callback);
            extractStream.on('error', callback);
            extractStream.on('finish', callback);
```

I keep getting the following error in some cases. The only difference between the case where things fail and where things don't fail is when the tarball already exists on disk before running the script (doesn't fail) and when i create the tarball and try to extract it (but only after the finish event on the `tar.pack(nodeModulesPath)`). I've run a fs.existsSync call before the code above to confirm that the tarball exists and the node modules path does not.

```
TypeError: Cannot read property 'corked' of undefined
    at Writable.end (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:429:12)
    at emptyStream (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:18:5)
    at onheader (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:135:34)
    at Extract._write (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:207:8)
    at doWrite (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Writable.write (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Gunzip.pipeOnReadable (_stream_readable.js:642:5)
```

This appears to be caused by the fact that `_writableState` is on the `_parent` property of the Source instance and not on the stream object itself. 

I tried adding a line to the source instantiation to pass this property through so it's available in `s.end()`, but then I get the following error:

```
Error: write after end
    at writeAfterEnd (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at Writable.write (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at Writable.end (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:426:10)
    at Extract._write (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:203:12)
    at Extract._continue (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:171:28)
    at oncontinue (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:62:10)
    at onheader (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:143:5)
    at Extract._write (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:207:8)
    at Extract._continue (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:171:28)
    at oncontinue (/Users/andrewdeandrade/code/unpm-install/node_modules/tar-fs/node_modules/tar-stream/extract.js:62:10)
```

My first intuition is that https://github.com/mafintosh/tar-stream/blob/master/extract.js#L31 should read `PassThrough.call(this, self);`, but that didn't fix the problem either (but still might be something you want to add)

I tried checking the value of _writableState all the way through the instantiation stack. It's defined at the end of the constructor function for Writable(), but is undefined after the `Writable.call(options)` in the instantiation function of Duplex.

Any ideas on what could be causing this and how to fix it?

**Comment by malandrew** [comment]
Okay.... did more debugging and here's the problem in the fail case. On this line https://github.com/iojs/readable-stream/blob/master/lib/_stream_writable.js#L143 both tests fail creating a new instance. In the success case, the object is an instance of Duplex. AFAICT this is the result of the circular dependencies. Trying to figure out how to solve this. Any ideas?

**Comment by malandrew** [comment]
The source of this problem is fixed in the newest version of readable-stream. I submitted a PR on tar-stream updating this dependency.

**Comment by malandrew** [comment]
Uggg... this isn't completely fixed yet. Upgrading to 1.0.33 of readable stream let it advance one entry, but now I'm getting an error in Writable.prototype.end where _writableState isn't available. This time I've traced the problem to this line: https://github.com/mafintosh/tar-stream/blob/master/pack.js#L41

For some reason that call to Writable.call(this); is being executed in such a way that the `require('./_stream_duplex');` call on line https://github.com/iojs/readable-stream/blob/master/lib/_stream_writable.js#L51 is causing the _stream_duplex.js file to be evaluated twice. 

If I put `console.log('DUPLEX EVALUATED');` at the top level of _stream_duplex.js, I see `DUPLEX EVALUATED` printed to the terminal twice.

**Comment by malandrew** [comment]
Found the cause, uber/npm-shrinkwrap resets the npm cache internally causing readable-streams to fail

https://github.com/uber/npm-shrinkwrap/issues/59

**Comment by malandrew** [comment]
Closing since this is not a tar-stream issue.
