### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by mirkods** [mafintosh/tar-stream#34]
Hi,
I must generate a dynamic tar file from a S3 directory and as Matteo Collina suggested me I'm using yours fantastic module for tar with pump in the following way:

```javascript
// this contain all files present in the directory
var files = [];
async.eachSeries(files, function(data, callback){
     // is an s3 file stream created with this module https://github.com/jb55/s3-blob-store
    var stream = store.createReadStream({ key: data.Key });
    var pack = tar.pack();
    var entry = pack.entry({ name: data.Key, size:data.Size }, function(err){
        if (err) console.log(err);
    });

    pump(stream, entry, function(err){
        if (err) console.log(err);
        if (tmp_count === files)
	      pack.finalize();
        callback();
    })

    pump(pack, res, function(err){
        if (err) console.log(err);
    })
}, function(err){
    if (err) console.log(err);
    req.end();
})
```

this code generate the following stack trace:

```javascript
Error: invalid header
    at Object.exports.decode (/tar-fs/node_modules/tar-stream/headers.js:205:40)
    at onheader (/tar-fs/node_modules/tar-stream/extract.js:103:39)
    at Extract._write (/tar-fs/node_modules/tar-stream/extract.js:206:8)
    at Extract._continue (/tar-fs/node_modules/tar-stream/extract.js:170:28)
    at oncontinue (/tar-fs/node_modules/tar-stream/extract.js:61:10)
    at ondrain (/tar-fs/node_modules/tar-stream/extract.js:81:5)
    at Extract._write (/tar-fs/node_modules/tar-stream/extract.js:206:8)
    at doWrite (/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/tar-fs/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

What you think about? I'm doing errors in my code or is there a problem?

Regards

**Comment by mirkods** [comment]
I have resolve it, my mistake! Sorry and congrats again for your libraries!

**Comment by mafintosh** [comment]
awesome :+1:

**Comment by hayes** [comment]
for future people with similar issues, make sure your stream is not gziped!
```javascript
targzStream
  .pipe(require('zlib').createGunzip())
  .pipe(tar.extract())
```
